version: '3'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    image: autodeployx_backend_staging

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8081:80"  # Staging Port
    depends_on:
      - backend
    restart: unless-stopped
