version: '3'

services:
  backend:
    build: ./backend
    image: autodeployx_backend_prod

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"    # Production Port
    depends_on:
      - backend 
