services:
  backend:
    build: ./backend
    restart: unless-stopped
    image: autodeployx_backend_staging

  nginx:
    image: nginx:alpine   
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/share/nginx/html   
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    restart: unless-stopped
